import { Link } from "@tanstack/react-router";
import { Check, ArrowRight } from "lucide-react";
import livingRoom from "@/assets/smart-living-room.jpg";
import cinema from "@/assets/private-cinema.jpg";
import outdoor from "@/assets/outdoor-av.jpg";
import { Button } from "@/components/ui/button";
import { FinalCta, PageHero } from "@/components/site-shell";
import { areas, contact, services } from "@/lib/site-data";

export function AboutPage() { return <><PageHero eyebrow="About us" title="Technology should complement the way you live." description="Home Cinema Center brings design thinking, technical expertise and local accountability to every project in Marin County." image={livingRoom} /><section className="py-24"><div className="mx-auto grid max-w-7xl gap-16 px-5 lg:grid-cols-2 lg:px-8"><div><h2 className="text-4xl font-medium">A better experience, from first conversation to final calibration.</h2><p className="mt-6 leading-8 text-muted-foreground">We listen before we specify. Our team studies the space, learns how you want to use it and designs an integrated system that supports your life without competing with the architecture.</p></div><div className="space-y-5">{["Custom system design, never one-size-fits-all packages","Respectful collaboration with homeowners and trade partners","Clean installation, precise programming and careful calibration","Responsive local service long after the project is complete"].map((item) => <div key={item} className="flex gap-4 border-b border-border pb-5"><Check className="shrink-0 text-primary" /><span>{item}</span></div>)}</div></div></section><FinalCta /></> }

export function ServicesPage() { return <><PageHero eyebrow="Services" title="One expert partner for every connected experience." description="From dedicated cinema to networking, lighting, shades and surveillance, each system is planned as part of one thoughtful whole." image={cinema} /><section className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid gap-px border border-border bg-border md:grid-cols-2">{services.map((service) => { const Icon=service.icon; return <article key={service.title} className="bg-background p-8 md:p-10"><Icon className="text-primary" /><h2 className="mt-8 text-2xl font-medium">{service.title}</h2><p className="mt-4 leading-7 text-muted-foreground">{service.description}</p><p className="mt-5 text-sm text-foreground/80">Benefit: a reliable, carefully integrated result that is simpler to use and easier to support.</p></article>})}</div><div className="mt-16 grid gap-5 md:grid-cols-3"><Button asChild variant="premiumOutline" size="xl"><Link to="/home-theater">Home Theater</Link></Button><Button asChild variant="premiumOutline" size="xl"><Link to="/smart-home">Smart Home</Link></Button><Button asChild variant="premiumOutline" size="xl"><Link to="/residential-commercial">Residential & Commercial</Link></Button></div></div></section><FinalCta /></> }

export function PortfolioPage() { const projects=[[livingRoom,"West Marin Smart Residence","Whole-home audio · Lutron lighting · motorized shades"],[cinema,"Novato Private Cinema","Projection · acoustic design · immersive audio"],[outdoor,"Marin Hillside Retreat","Outdoor audio · lighting · networking"]] as const; return <><PageHero eyebrow="Portfolio" title="Integrated technology, seen through the spaces it serves." description="A selection of residential AV, lighting, control and entertainment environments designed for Marin living." /><section className="py-24"><div className="mx-auto grid max-w-7xl gap-12 px-5 md:grid-cols-2 lg:px-8">{projects.map(([image,title,detail], index) => <article key={title} className={index===0 ? "md:col-span-2" : ""}><img src={image} alt={title} width="1200" height="800" loading="lazy" className={`w-full object-cover ${index===0?"aspect-[16/8]":"aspect-[4/3]"}`} /><p className="mt-5 text-xs uppercase tracking-widest text-primary">Marin County</p><h2 className="mt-2 text-2xl font-medium">{title}</h2><p className="mt-2 text-sm text-muted-foreground">{detail}</p></article>)}</div></section><FinalCta title="Imagine what’s possible in your space." /></> }

export function BlogPage() { const posts=[["Planning a Home Theater That Fits Your Space","Room proportions, viewing distance and acoustics matter more than any single component."],["Why a Strong Home Network Comes First","The foundation behind dependable streaming, smart control, cameras and connected work."],["Lighting Scenes That Change How a Home Feels","A thoughtful approach to daily routines, entertaining, artwork and natural light."],["Motorized Shades: Comfort, Privacy and Protection","How automated window treatments manage glare, temperature and interior finishes."]]; return <><PageHero eyebrow="Insights" title="Clear guidance for better technology decisions." description="Practical perspectives from our work in home theater, smart home design, lighting and connected living." /><section className="py-24"><div className="mx-auto grid max-w-7xl gap-px border border-border bg-border px-0 md:grid-cols-2">{posts.map(([title,desc],i)=><article key={title} className="bg-background p-8 md:p-12"><span className="text-xs font-semibold text-primary">0{i+1}</span><h2 className="mt-8 text-2xl font-medium">{title}</h2><p className="mt-4 leading-7 text-muted-foreground">{desc}</p><Link to="/contact" className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-primary">Ask an expert <ArrowRight className="size-4" /></Link></article>)}</div></section><FinalCta title="Have a project question? Ask a local expert." /></> }

export function ContactPage() { return <><PageHero eyebrow="Contact us" title="Tell us what you want your space to do." description="Whether you are planning a new build, upgrading one room or looking for expert service, our Novato team is ready to help." /><section className="py-24"><div className="mx-auto grid max-w-7xl gap-16 px-5 lg:grid-cols-2 lg:px-8"><div><h2 className="text-3xl font-medium">Start the conversation.</h2><div className="mt-8 space-y-5"><a href={contact.phoneHref} className="block border-b border-border pb-5 text-xl hover:text-primary">{contact.phone}</a><a href={contact.emailHref} className="block border-b border-border pb-5 text-xl hover:text-primary">{contact.email}</a><p className="text-muted-foreground">Serving Novato, Marin County and surrounding communities.</p></div></div><form className="grid gap-5" action={contact.emailHref} method="get"><label className="grid gap-2 text-sm">Name<input name="name" required className="h-12 border border-input bg-card px-4 outline-none focus:border-primary" /></label><label className="grid gap-2 text-sm">Email<input name="email" type="email" required className="h-12 border border-input bg-card px-4 outline-none focus:border-primary" /></label><label className="grid gap-2 text-sm">Phone<input name="phone" type="tel" className="h-12 border border-input bg-card px-4 outline-none focus:border-primary" /></label><label className="grid gap-2 text-sm">How can we help?<textarea name="body" required rows={6} className="border border-input bg-card p-4 outline-none focus:border-primary" /></label><Button type="submit" variant="premium" size="xl">Request a Free Quote</Button></form></div></section></> }

export function FeaturePage({ eyebrow, title, description, image, benefits }: { eyebrow:string; title:string; description:string; image:string; benefits:string[] }) { return <><PageHero eyebrow={eyebrow} title={title} description={description} image={image} /><section className="py-24"><div className="mx-auto grid max-w-7xl gap-16 px-5 lg:grid-cols-2 lg:px-8"><div><h2 className="text-4xl font-medium">Designed around the space. Built around you.</h2><p className="mt-6 leading-8 text-muted-foreground">We coordinate the details—from infrastructure and equipment placement to programming and final tuning—so the finished system is capable, discreet and natural to use.</p></div><div className="grid gap-4">{benefits.map((benefit)=><div key={benefit} className="flex gap-4 border-b border-border pb-4"><Check className="shrink-0 text-primary" /><span>{benefit}</span></div>)}</div></div></section><FinalCta /></> }

export function ServiceAreasPage() { return <><PageHero eyebrow="Service areas" title="Local service throughout Marin County." description="Home Cinema Center is based in Novato and serves homeowners, designers, builders and businesses across Marin and nearby communities." image={outdoor} /><section className="py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid gap-px border border-border bg-border sm:grid-cols-2 md:grid-cols-3">{areas.map((area)=><div key={area} className="bg-background p-7"><h2 className="text-xl font-medium">{area}, CA</h2><p className="mt-2 text-sm text-muted-foreground">Home theater, audio, lighting, shades, networking and smart-home installation.</p></div>)}</div></div></section><FinalCta title="Expert help, close to home." /></> }